### ISSUE TITLE
Include Cuda in Pipeline/Scheduler/DataloaderTest

### ISSUE THREAD

**Issue by cesarali** [cesarali/graph-bridges#1]
For now we just need to check that in the ctdd test for pipeline and scheduler includes the cuda.

Check the line

https://github.com/cesarali/graph-bridges/blob/1de944bf0066cd7ef4851060e232f0b659a6fb09/tests/pipelines/ctdd/test_ctdd.py#L17C1-L18C1

**Comment by dfaroughy** [comment]
fixed for loss in

https://github.com/cesarali/graph-bridges/blob/39601fe4b1bfbbe2fae0e5ac9078c99d4780016e/tests/loss/test_ctdd_loss.py#L27C1-L30C30
